HOD_params:
  LRG_params:
    alpha: 1.02
    alpha_c: 0.2
    alpha_s: 0.88
    ic: 1.0
    kappa: 1.27
    logM1: 13.81
    logM_cut: 12.67
    sigma: 0.02
    profile_code: 1
  tracer_flags:
    ELG: false
    LRG: true
    QSO: false
  use_particles: false
  use_profiles: true
  want_AB: true
  want_rsd: true
  want_dv: true
  dv_draw_L: /global/homes/s/siyizhao/projects/fihobi/data/dv_draws/LRG_z0.6-0.8_CDF.npz
  write_to_disk: false
clustering_params:
  bin_params:
    logmax: 1.5
    logmin: -1.0
    nbins: 15
  clustering_type: all
  pi_bin_size: 40
  pimax: 40
data_params:
  tracer_combos:
    LRG_LRG:
      path2cov: /global/homes/s/siyizhao/projects/fihobi/data/for_hod/v2_rp6s11/cov_LRG_0.6_0.8_cut.dat
      path2wp: /global/homes/s/siyizhao/projects/fihobi/data/for_hod/v2_rp6s11/wp_LRG_0.6_0.8_cut.dat
      path2xi02: /global/homes/s/siyizhao/projects/fihobi/data/for_hod/v2_rp6s11/xi02_LRG_0.6_0.8_cut.dat
  tracer_density_mean:
    LRG: 0.0005247
  tracer_density_std:
    LRG: 5.2470000000000004e-05
nthread: 64
prepare_sim:
  Nparallel_load: 18
sim_params:
  cleaned_halos: true
  output_dir: /pscratch/sd/s/siyizhao/desi-dr2-hod/loa-v2_HODv2/mocks_base-A-dv/
  sim_dir: /global/cfs/projectdirs/desi/cosmosim/Abacus/
  sim_name: Abacus_pngbase_c302_ph000
  subsample_dir: /pscratch/sd/s/siyizhao/AbacusSummit/subsample_desidr2_profile_withAB/
  z_mock: 0.725
  force_mt: true
chain_params:
  chain_prefix: chain_v2_
  output_dir: /pscratch/sd/s/siyizhao/desi-dr2-hod/loa-v2_HODv2/LRG-fnl100/z2_base-A-dv/
  nlive: 500
  tol: 0.5
  labels:
  - \log M_{\text{cut}}
  - \log M_1
  - \log \sigma
  - \alpha
  - \kappa
  - \alpha_{\text{c}}
  - \alpha_{\text{s}}
  - A_{\text{cent}}
  - A_{\text{sat}}
fit_params:
  LRG:
    logM_cut:
    - 0
    - 11.0
    - 15.0
    - flat
    logM1:
    - 1
    - 10.0
    - 18.0
    - flat
    sigma:
    - 2
    - -4.0
    - 0.0
    - log
    alpha:
    - 3
    - -1.0
    - 3.0
    - flat
    kappa:
    - 4
    - 0.0
    - 6.0
    - flat
    alpha_c:
    - 5
    - -4.0
    - 1.0
    - log
    alpha_s:
    - 6
    - -4.0
    - 1.0
    - log
    Acent:
    - 7
    - -10.0
    - 10.0
    - flat
    Asat:
    - 8
    - -15.0
    - 15.0
    - flat
