HOD_params:
  tracer_flags:
    ELG: false
    LRG: false
    QSO: true
  use_particles: false
  use_profiles: true
  want_AB: true
  want_rsd: true
  want_dv: true # redshift error, recommended to be true
  write_to_disk: false
  QSO_params:
    logM_cut: 12.03
    logM1: 13.11
    sigma: 0.08
    alpha: 1.03
    kappa: 0.39
    alpha_c: 0.92
    alpha_s: 2.7
    ic: 1.0
    profile_code: 1
  dv_draw_Q: /global/cfs/projectdirs/desi/users/jiaxiyu/repeated_observations/EDR_vs_Y3/LSS-scripts_repeats/QSO_z0.8-2.1_CDF.npz
clustering_params:
  bin_params:
    logmax: 1.5
    logmin: -1.5
    nbins: 18
  clustering_type: all
  pi_bin_size: 40
  pimax: 40
nthread: 64
prepare_sim:
  Nparallel_load: 18
sim_params:
  cleaned_halos: true
  output_dir: /pscratch/sd/s/siyizhao/desi-dr2-hod/mocks/
  sim_dir: /global/cfs/projectdirs/desi/cosmosim/Abacus/
  sim_name: AbacusSummit_base_c000_ph000
  subsample_dir: /pscratch/sd/s/siyizhao/AbacusSummit/subsample_desidr2_profile_withAB/
  z_mock: 1.4
  force_mt: true
# fitting data
data_params:
  tracer_combos:
    QSO_QSO:
      path2cov: /global/homes/s/siyizhao/projects/fihobi/data/for_hod/v1.1/cov_QSO_0.8_2.1_cut.dat
      path2wp: /global/homes/s/siyizhao/projects/fihobi/data/for_hod/v1.1/wp_QSO_0.8_2.1_cut.dat
      path2xi02: /global/homes/s/siyizhao/projects/fihobi/data/for_hod/v1.1/xi02_QSO_0.8_2.1_cut.dat
  tracer_density_mean:
    QSO: 3.287e-05
  tracer_density_std:
    QSO: 3.287e-06
# sampler settings
chain_params:
  chain_prefix: QSO_zall_base
  output_dir: /pscratch/sd/s/siyizhao/desi-dr2-hod/QSO/
  nlive: 500
  tol: 0.5
  labels: 
    - '\log M_{\text{cut}}'
    - '\log M_1'
    - '\sigma'
    - '\alpha'
    - '\kappa'
    - '\alpha_{\text{c}}'
    - '\alpha_{\text{s}}'
fit_params:
  QSO:
    logM_cut:
    - 0
    - 11.0
    - 14.0
    logM1:
    - 1
    - 12.5
    - 15.5
    sigma:
    - 2
    - 0.001
    - 2.0
    alpha:
    - 3
    - 0.0
    - 3.0
    kappa:
    - 4
    - 0.0
    - 5.0
    alpha_c:
    - 5
    - 0.0
    - 3.0
    alpha_s:
    - 6
    - 0.0
    - 5.0
